# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Contact,
        ContactContact,
        ContactSegmentsItem,
        ErrorResponse,
        ErrorResponseError,
        ErrorResponseErrorDetailsItem,
        PaginationMeta,
        Segment,
    )
    from .errors import BadRequestError, ForbiddenError, NotFoundError, UnauthorizedError
    from . import contacts, segments
    from .client import AsyncInformly, Informly
    from .contacts import (
        CreateContactResponse,
        DeleteContactResponse,
        DeleteContactsResponse,
        DeleteContactsResponseData,
        GetContactResponse,
        ListContactsResponse,
        UpdateContactResponse,
    )
    from .environment import InformlyEnvironment
    from .segments import ListSegmentsResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncInformly": ".client",
    "BadRequestError": ".errors",
    "Contact": ".types",
    "ContactContact": ".types",
    "ContactSegmentsItem": ".types",
    "CreateContactResponse": ".contacts",
    "DeleteContactResponse": ".contacts",
    "DeleteContactsResponse": ".contacts",
    "DeleteContactsResponseData": ".contacts",
    "ErrorResponse": ".types",
    "ErrorResponseError": ".types",
    "ErrorResponseErrorDetailsItem": ".types",
    "ForbiddenError": ".errors",
    "GetContactResponse": ".contacts",
    "Informly": ".client",
    "InformlyEnvironment": ".environment",
    "ListContactsResponse": ".contacts",
    "ListSegmentsResponse": ".segments",
    "NotFoundError": ".errors",
    "PaginationMeta": ".types",
    "Segment": ".types",
    "UnauthorizedError": ".errors",
    "UpdateContactResponse": ".contacts",
    "contacts": ".contacts",
    "segments": ".segments",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncInformly",
    "BadRequestError",
    "Contact",
    "ContactContact",
    "ContactSegmentsItem",
    "CreateContactResponse",
    "DeleteContactResponse",
    "DeleteContactsResponse",
    "DeleteContactsResponseData",
    "ErrorResponse",
    "ErrorResponseError",
    "ErrorResponseErrorDetailsItem",
    "ForbiddenError",
    "GetContactResponse",
    "Informly",
    "InformlyEnvironment",
    "ListContactsResponse",
    "ListSegmentsResponse",
    "NotFoundError",
    "PaginationMeta",
    "Segment",
    "UnauthorizedError",
    "UpdateContactResponse",
    "contacts",
    "segments",
]
