# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ContactContact(UniversalBaseModel):
    firstname: typing.Optional[str] = None
    lastname: typing.Optional[str] = None
    jobtitle: typing.Optional[str] = None
    company: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
