# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .error_response_error_details_item import ErrorResponseErrorDetailsItem


class ErrorResponseError(UniversalBaseModel):
    code: str
    message: str
    details: typing.Optional[typing.List[ErrorResponseErrorDetailsItem]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
