# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class Segment(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the segment
    """

    title: str = pydantic.Field()
    """
    Segment name
    """

    color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hex color for the segment
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
