# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .contact import Contact
    from .contact_contact import ContactContact
    from .contact_segments_item import ContactSegmentsItem
    from .error_response import ErrorResponse
    from .error_response_error import ErrorResponseError
    from .error_response_error_details_item import ErrorResponseErrorDetailsItem
    from .pagination_meta import PaginationMeta
    from .segment import Segment
_dynamic_imports: typing.Dict[str, str] = {
    "Contact": ".contact",
    "ContactContact": ".contact_contact",
    "ContactSegmentsItem": ".contact_segments_item",
    "ErrorResponse": ".error_response",
    "ErrorResponseError": ".error_response_error",
    "ErrorResponseErrorDetailsItem": ".error_response_error_details_item",
    "PaginationMeta": ".pagination_meta",
    "Segment": ".segment",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Contact",
    "ContactContact",
    "ContactSegmentsItem",
    "ErrorResponse",
    "ErrorResponseError",
    "ErrorResponseErrorDetailsItem",
    "PaginationMeta",
    "Segment",
]
