# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ContactContact(UniversalBaseModel):
    firstname: typing.Optional[str] = pydantic.Field(default=None)
    """
    First name of the contact
    """

    lastname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last name of the contact
    """

    jobtitle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Job title of the contact
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company or organization name
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
