# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class ContactSegmentsItem(UniversalBaseModel):
    segment_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="segmentId"), pydantic.Field(alias="segmentId", description="Segment identifier")
    ]
    assigned_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="assignedAt"),
        pydantic.Field(alias="assignedAt", description="When the segment was assigned"),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
