# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ErrorResponseErrorDetailsItem(UniversalBaseModel):
    path: str = pydantic.Field()
    """
    JSON path to the invalid field
    """

    message: str = pydantic.Field()
    """
    Validation error message for this field
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
