# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class DeleteContactsResponseData(UniversalBaseModel):
    count: float = pydantic.Field()
    """
    Number of contacts deleted
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
