# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .delete_contacts_response_data import DeleteContactsResponseData


class DeleteContactsResponse(UniversalBaseModel):
    data: DeleteContactsResponseData

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
