# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from ...types.contact import Contact
from ...types.pagination_meta import PaginationMeta


class ListContactsResponse(UniversalBaseModel):
    data: typing.List[Contact]
    meta: PaginationMeta

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
