# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSegmentsClient, RawSegmentsClient
from .types.list_segments_response import ListSegmentsResponse


class SegmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSegmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSegmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSegmentsClient
        """
        return self._raw_client

    def list_segments(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListSegmentsResponse:
        """
        Returns all segments available in the organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSegmentsResponse
            List of segments

        Examples
        --------
        from informly-sdk import Informly

        client = Informly(token="YOUR_TOKEN", )
        client.segments.list_segments()
        """
        _response = self._raw_client.list_segments(request_options=request_options)
        return _response.data


class AsyncSegmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSegmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSegmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSegmentsClient
        """
        return self._raw_client

    async def list_segments(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListSegmentsResponse:
        """
        Returns all segments available in the organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSegmentsResponse
            List of segments

        Examples
        --------
        import asyncio

        from informly-sdk import AsyncInformly

        client = AsyncInformly(token="YOUR_TOKEN", )
        async def main() -> None:
            await client.segments.list_segments()
        asyncio.run(main())
        """
        _response = await self._raw_client.list_segments(request_options=request_options)
        return _response.data
