# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawContactsClient, RawContactsClient
from .types.create_contact_response import CreateContactResponse
from .types.get_contact_response import GetContactResponse
from .types.list_contacts_response import ListContactsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ContactsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawContactsClient
        """
        return self._raw_client

    def list_contacts(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListContactsResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListContactsResponse
            List of contacts

        Examples
        --------
        from informly import InformlyClient

        client = InformlyClient(
            token="YOUR_TOKEN",
        )
        client.contacts.list_contacts()
        """
        _response = self._raw_client.list_contacts(page=page, page_size=page_size, request_options=request_options)
        return _response.data

    def create_contact(
        self,
        *,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        firstname: typing.Optional[str] = OMIT,
        lastname: typing.Optional[str] = OMIT,
        jobtitle: typing.Optional[str] = OMIT,
        company: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateContactResponse:
        """
        Parameters
        ----------
        email : typing.Optional[str]

        phone : typing.Optional[str]

        firstname : typing.Optional[str]

        lastname : typing.Optional[str]

        jobtitle : typing.Optional[str]

        company : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateContactResponse
            Contact created

        Examples
        --------
        from informly import InformlyClient

        client = InformlyClient(
            token="YOUR_TOKEN",
        )
        client.contacts.create_contact()
        """
        _response = self._raw_client.create_contact(
            email=email,
            phone=phone,
            firstname=firstname,
            lastname=lastname,
            jobtitle=jobtitle,
            company=company,
            request_options=request_options,
        )
        return _response.data

    def get_contact(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetContactResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetContactResponse
            Contact details

        Examples
        --------
        from informly import InformlyClient

        client = InformlyClient(
            token="YOUR_TOKEN",
        )
        client.contacts.get_contact(
            id="id",
        )
        """
        _response = self._raw_client.get_contact(id, request_options=request_options)
        return _response.data


class AsyncContactsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawContactsClient
        """
        return self._raw_client

    async def list_contacts(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListContactsResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListContactsResponse
            List of contacts

        Examples
        --------
        import asyncio

        from informly import AsyncInformlyClient

        client = AsyncInformlyClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.list_contacts()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_contacts(
            page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create_contact(
        self,
        *,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        firstname: typing.Optional[str] = OMIT,
        lastname: typing.Optional[str] = OMIT,
        jobtitle: typing.Optional[str] = OMIT,
        company: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateContactResponse:
        """
        Parameters
        ----------
        email : typing.Optional[str]

        phone : typing.Optional[str]

        firstname : typing.Optional[str]

        lastname : typing.Optional[str]

        jobtitle : typing.Optional[str]

        company : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateContactResponse
            Contact created

        Examples
        --------
        import asyncio

        from informly import AsyncInformlyClient

        client = AsyncInformlyClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.create_contact()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_contact(
            email=email,
            phone=phone,
            firstname=firstname,
            lastname=lastname,
            jobtitle=jobtitle,
            company=company,
            request_options=request_options,
        )
        return _response.data

    async def get_contact(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetContactResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetContactResponse
            Contact details

        Examples
        --------
        import asyncio

        from informly import AsyncInformlyClient

        client = AsyncInformlyClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.get_contact(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_contact(id, request_options=request_options)
        return _response.data
